### ISSUE TITLE
Semver

### ISSUE THREAD

**Issue by jongotlin** [billogram/billogram-v2-api-php-lib#10]
Please consider using semver versioning (http://semver.org/)

**Comment by AndreasHogstrom** [comment]
Absolutely, that is the intention for the **next** release.

**Comment by jongotlin** [comment]
Next major? If then, please write how to configure composer require to get latest patch (no bc break).

**Comment by AndreasHogstrom** [comment]
Since we haven't been using semantic versioning earlier I'm not sure you can do that right at this moment. But we could re-release `v1.12` as semantic version `1.12.0` soon, and you can go from there.

**Comment by jongotlin** [comment]
:+1:
