### ISSUE TITLE
Add support for Httplug

### ISSUE THREAD

**Issue by Nyholm** [billogram/billogram-v2-api-php-lib#12]
At the moment you are using fopen to send HTTP requests. A lot of what you are doing is like waking across the bridge for water. 
Would you be open for using a standard way of sending HTTP requests by using [HTTPlug](http://docs.php-http.org/en/latest/)?

This will reduce your code by at least 50% and will also solve the issue in #9.

**Comment by AndreasHogstrom** [comment]
Thank you for the suggestion. At this time we're not so keen about adding external dependencies to this module, but we will consider the feedback for the next (as of yet unplanned) version.
