### ISSUE TITLE
Create an adapter for Payum

### ISSUE THREAD

**Issue by Nyholm** [billogram/billogram-v2-api-php-lib#14]
Is there any plans for an extension/adapter to Payum? Would you willing to accept a new package like that?

**Comment by AndreasHogstrom** [comment]
We have no plans to release and support an extension to Payum at the moment.

The community is free to create integrations for the systems they are using as long as they follow the Billogram terms and conditions.

**Comment by Nyholm** [comment]
Thank you Andereas for your answers. 

> Would you willing to accept a new package like that?

This is me offering to help you, your brand, your company to have a better open source presence.
