### ISSUE TITLE
allow_url_fopen setting does not work with code

### ISSUE THREAD

**Issue by insperedia** [billogram/billogram-v2-api-php-lib#17]
Hi,

using http wrapper in streams considered as potential security risk. On our server we use allow_url_fopen=0 to block possibility to use url instead filenames. The recomended method to make remote requests in PHP  is to use curl directly. 
**Anyway there would be no problem to override Api::httpRequest if it would have protected access modifier.**

**Comment by Nyholm** [comment]
The PR #16 will solve this issue.

**Comment by insperedia** [comment]
Hi @Nyholm, nice to see meet you not only on PHP MeetUps but also on GitHub :)

**Comment by insperedia** [comment]
Regarding HTTPlug I would agree with developer. There no need in additional depencies.
